### ISSUE TITLE
Wifi interface is missing after zen 5.5.2

### ISSUE THREAD

**Issue by bkalpa9** [zen-kernel/zen-kernel#164]
$dmesg | grep iwlwifi
[    5.915227] iwlwifi 0000:02:00.0: enabling device (0000 -> 0002)
[    5.928645] iwlwifi 0000:02:00.0: loaded firmware version 29.163394017.0 op_mode iwlmvm
[    6.087468] iwlwifi 0000:02:00.0: Detected Intel(R) Dual Band Wireless AC 3168, REV=0x220
[    6.108023] iwlwifi 0000:02:00.0: Can't parse phy_sku in B0, empty sections
[    6.108676] iwlwifi 0000:02:00.0: Failed to read NVM: -61
[    6.109317] iwlwifi 0000:02:00.0: Collecting data: trigger 16 fired.
[    6.110968] iwlwifi 0000:02:00.0: Start IWL Error Log Dump:
[    6.111501] iwlwifi 0000:02:00.0: Status: 0x00000040, count: 6
[    6.112108] iwlwifi 0000:02:00.0: Loaded firmware version: 29.163394017.0
[    6.112634] iwlwifi 0000:02:00.0: 0x00000084 | NMI_INTERRUPT_UNKNOWN       
[    6.113159] iwlwifi 0000:02:00.0: 0x000002F0 | trm_hw_status0
[    6.113681] iwlwifi 0000:02:00.0: 0x00000000 | trm_hw_status1
[    6.114203] iwlwifi 0000:02:00.0: 0x0004171E | branchlink2
[    6.114808] iwlwifi 0000:02:00.0: 0x000446B2 | interruptlink1
[    6.115396] iwlwifi 0000:02:00.0: 0x00004936 | interruptlink2
[    6.118060] iwlwifi 0000:02:00.0: 0x00000000 | data1
[    6.118595] iwlwifi 0000:02:00.0: 0x00000080 | data2
[    6.119052] iwlwifi 0000:02:00.0: 0x07030000 | data3
[    6.120021] iwlwifi 0000:02:00.0: 0x00000000 | beacon time
[    6.120570] iwlwifi 0000:02:00.0: 0x00002009 | tsf low
[    6.121120] iwlwifi 0000:02:00.0: 0x00000000 | tsf hi
[    6.121669] iwlwifi 0000:02:00.0: 0x00000000 | time gp1
[    6.122197] iwlwifi 0000:02:00.0: 0x00002009 | time gp2
[    6.123594] iwlwifi 0000:02:00.0: 0x00000009 | uCode revision type
[    6.124094] iwlwifi 0000:02:00.0: 0x0000001D | uCode version major
[    6.124604] iwlwifi 0000:02:00.0: 0x09BD31E1 | uCode version minor
[    6.125076] iwlwifi 0000:02:00.0: 0x00000220 | hw version
[    6.125505] iwlwifi 0000:02:00.0: 0x00C89200 | board version
[    6.126803] iwlwifi 0000:02:00.0: 0x00110188 | hcmd
[    6.127074] iwlwifi 0000:02:00.0: 0x00022000 | isr0
[    6.127353] iwlwifi 0000:02:00.0: 0x00000000 | isr1
[    6.127781] iwlwifi 0000:02:00.0: 0x00000002 | isr2
[    6.127973] iwlwifi 0000:02:00.0: 0x004000C0 | isr3
[    6.128155] iwlwifi 0000:02:00.0: 0x00000000 | isr4
[    6.128333] iwlwifi 0000:02:00.0: 0x00110188 | last cmd Id
[    6.128511] iwlwifi 0000:02:00.0: 0x00000000 | wait_event
[    6.128685] iwlwifi 0000:02:00.0: 0x00002C01 | l2p_control
[    6.128872] iwlwifi 0000:02:00.0: 0x00000000 | l2p_duration
[    6.129036] iwlwifi 0000:02:00.0: 0x00000000 | l2p_mhvalid
[    6.129197] iwlwifi 0000:02:00.0: 0x00000000 | l2p_addr_match
[    6.129427] iwlwifi 0000:02:00.0: 0x00000007 | lmpm_pmg_sel
[    6.129767] iwlwifi 0000:02:00.0: 0x07100855 | timestamp
[    6.130102] iwlwifi 0000:02:00.0: 0x00341018 | flow_handler
[    6.130574] iwlwifi 0000:02:00.0: Fseq Registers:
[    6.130979] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_ERROR_CODE
[    6.131388] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_TOP_INIT_VERSION
[    6.131783] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_CNVIO_INIT_VERSION
[    6.132192] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_OTP_VERSION
[    6.132593] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_TOP_CONTENT_VERSION
[    6.132991] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_ALIVE_TOKEN
[    6.133391] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_CNVI_ID
[    6.133798] iwlwifi 0000:02:00.0: 0x00000000 | FSEQ_CNVR_ID
[    6.134191] iwlwifi 0000:02:00.0: 0x00000000 | CNVI_AUX_MISC_CHIP
[    6.134592] iwlwifi 0000:02:00.0: 0x00000000 | CNVR_AUX_MISC_CHIP
[    6.135006] iwlwifi 0000:02:00.0: 0x00000000 | CNVR_SCU_SD_REGS_SD_REG_DIG_DCDC_VTRIM
[    6.135417] iwlwifi 0000:02:00.0: 0x00000000 | CNVR_SCU_SD_REGS_SD_REG_ACTIVE_VDIG_MIRROR
[    6.135858] iwlwifi 0000:02:00.0: Firmware not running - cannot dump error
[    6.148782] iwlwifi 0000:02:00.0: Failed to run INIT ucode: -61

**Comment by damentz** [comment]
According to the open bugzilla issue [1], we merged a patch [2] into 5.5/fixes that _should_ have fixed the issue.  The alternative fix is to revert this patch and the commit it tries to fix.

Can you verify on latest 5.5/master that wifi doesn't work?

[1] https://bugzilla.kernel.org/show_bug.cgi?id=206329
[2] https://github.com/zen-kernel/zen-kernel/commit/861efb65aab7813e01dd74bcaea6ef4bbbf3751d

**Comment by bkalpa9** [comment]
I am using latest 5.5.2-zen1-1-zen and problem still exists.. although i have found the pach message here https://patchwork.kernel.org/patch/11353871/ but it seems not applied yet.
Hope it will be resolved soon.

**Comment by bkalpa9** [comment]
Your source code at zen-kernel / drivers/ net/intel /iwlwifi/mvm/nvm.c does not reflect [2].
Please check it again.

**Comment by damentz** [comment]
Wait, why did you close this issue?  Is your 3168 initializing on your system?

**Comment by bkalpa9** [comment]
> Wait, why did you close this issue? Is your 3168 initializing on your system?
> 
> EDIT: Also, per the commit message, 5.5.2-zen2 was the first zen patch that included this hotfix. That means you would need to upgrade to get it (6 days ago): https://github.com/zen-kernel/zen-kernel/releases/tag/v5.5.2-zen2

I updated to v 5.5.2-zen2 and its loading the driver for intel 3168 wireless card, another problem I faced was It failed to compile nvidia-dkms and vbox-dkms but after updating GCC , gcc-libs it compiled and working fine. 
P.s. I installed kernel from Arch testing repo.
Thanks for your response.
