### ISSUE TITLE
Razer Blade 15 Advanced Edition (2021) randomly freezes when opening applications

### ISSUE THREAD

**Issue by jacobcantele** [zen-kernel/zen-kernel#210]
When using zen-kernel on a Garuda Linux Gnome laptop, I've found that the laptop randomly freezes when opening applications and does not recover. I cannot consistently make it happen, but it is multiple crashes per day. I've also found that when opening applications, even if the laptop doesn't crash, it always feels like it stutters for about 1 second before unfreezing. 

Is there a log file I can provide that would help with troubleshooting this? The issue does not happen when using other kernels.

**Comment by damentz** [comment]
This might be related to the Multigenerational LRU patches we merged recently.  Can you look for any stack traces by running `sudo journalctl -k -b -1`? (after a freeze and hard reboot).  You can also decrement the number for `-b` more to jump back further into your boot logs and find a session that's causing the kernel panic.

**Comment by damentz** [comment]
This looks like some type of incompatibility of the nvidia driver with kernel 5.12.  Have you tried using the TKG nvidia PKGBUILD?  It might get you a version of the driver that works better: https://github.com/Frogging-Family/nvidia-all

**Comment by jacobcantele** [comment]
so I did a bit more testing, and I definitely don't think this is the same as the nVidia error. I'm still having this issue even when I switch the laptop to the open source driver.

**Comment by df8oe** [comment]
I have memory issues with this kernel, too. I am using i7 with 8GB RAM / 16GB swap and if I start many applications system rans out of RAM. Applications are complaining about a lack of RAM or die simply. Swapping does not start - swap is unused. This isdefinitely rated to kernel: with older ZEN-kernels everything works fine, also with non-zen-kernels. To reproduce you only must start many applications until RAM is eaten up and then start some more...

**Comment by damentz** [comment]
The first release of Zen Kernel 5.14.1 had an unnecessary patch applied to MG-LRU that was only required in 5.13.  We reverted the change in https://github.com/zen-kernel/zen-kernel/commit/53b777120fd8b106261151b1a9e1e24a3c20b850 and released 5.14.1-zen2 (https://github.com/zen-kernel/zen-kernel/commit/53b777120fd8b106261151b1a9e1e24a3c20b850).

@df8oe can you try the latest kernel and see if that resolves your issue?

**Comment by df8oe** [comment]
You fixed it. Issues are gone with 5.14.1-zen2. Many thanks for your work!

**Comment by damentz** [comment]
@jacobcantele can you confirm if the original issue here is resolved in Zen 5.14?

**Comment by jacobcantele** [comment]
checking!

**Comment by heftig** [comment]
Has this improved?

**Comment by damentz** [comment]
This may have originally been related to a bad MG-LRU patch.  I'll mark this as resolved since multiple major kernel versions have come out since then.

Please submit a new issue if you are still having instability with nvidia with Zen Kernel.
