### ISSUE TITLE
GW2 w/ Futex2 on 5.13.1: CoherentUIHost going nuts on CPU usage (~11Cores)

### ISSUE THREAD

**Issue by Atemu** [zen-kernel/zen-kernel#217]
I have no knowledge or ability to debug this but this did not happen on 5.12, nor does it happen with 5.13.1 when using esync instead.

This makes the game nearly unplayable (low 20s) and stresses the whole CPU for no good reason.

**Comment by damentz** [comment]
@Atemu this _should_ be fixed now in 5.13/master.  We'll need to wait for @heftig to spin another build of `linux-zen`.

**Comment by Atemu** [comment]
Hi @damentz, thanks for looking into this. Unfortunately, it's still happening on 18cfd384ae87780a9ffd941df1bcfc8e0a2de26c though.

If you want to reproduce this for yourself, GW2's launcher also exhibits this behaviour and can easily be installed via Lutris without downloading the whole 50G game.

**Comment by damentz** [comment]
@Atemu thanks for giving the updated master branch a shot.  I sent André an email asking if he could provide a port of his futex2-proton working branch for v5.13 and pointed him to the problems you found in this issue.  Hopefully we can come out of this with a better futex2 than what we have on 5.12 :crossed_fingers:

**Comment by damentz** [comment]
@Atemu can you try 5.13/master again?  Per  André's recommendation, he suggested the patch by the `linux-tkg` folk at https://github.com/Frogging-Family/linux-tkg/blob/master/linux-tkg-patches/5.13/0007-v5.13-futex2_interface.patch.

 André pointed out that even though it's based on a much older futex2 patch set, since the futex2 patch is a work-in-progress, it's expected that there'll be regressions as new drafts come out.  Or TL;DR, this _should_ work now :crossed_fingers:

**Comment by damentz** [comment]
@Atemu Does latest Zen Kernel resolve CPU usage issues with GW2?

**Comment by damentz** [comment]
I'll mark this issue as resolved.  Zen Kernel is now using the same patch set used by TKG and XanMod.  If there was an issue with this patch then it would be affecting all kernels.  Let me know if there's an issue, otherwise I'm marking this as resolved.

**Comment by Atemu** [comment]
Yup, it's fixed now. Thanks!
